# Generated by Django 2.2.4 on 2020-02-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200228_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='zhonglei',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='商品SPU种类'),
            preserve_default=False,
        ),
    ]
